local solarized = {
  base03      = "#002b36",
  base02      = "#073642",
  base01      = "#586e75",
  base00      = "#657b83",
  base0       = "#839496",
  base1       = "#93a1a1",
  base2       = "#eee8d5",
  base3       = "#fdf6e3",
  yellow      = "#b58900",
  orange      = "#cb4b16",
  red         = "#dc322f",
  magenta     = "#d33682",
  violet      = "#6c71c4",
  blue        = "#268bd2",
  cyan        = "#2aa198",
  green       = "#719e07",
}

local colors = {
  fg = solarized.base01,
  bg = solarized.base3,
  alt_bg = solarized.base2,
  accent = solarized.magenta,
  white = solarized.base3,
  gray = solarized.base01,
  light_gray = solarized.base1,
  blue = solarized.blue,
  gray_blue = "#66899d",
  cyan = solarized.cyan,
  red = solarized.red,
  green = solarized.green,
  light_green = "#b2d77c",
  yellow = solarized.yellow,
  orange = solarized.orange,
  purple = "#bf83c1",
  pale_purple = "#7199ee",
  magenta = solarized.magenta,
  cursor_fg = "#515052",
  cursor_bg = "#AEAFAD",
  sign_add = solarized.green,
  sign_change = solarized.yellow,
  sign_delete = solarized.red,
  error_red = solarized.red,
  warning_orange = solarized.yellow,
  info_yellow = solarized.yellow,
  hint_blue = solarized.blue,
  purple_test = "#ff00ff",
  cyan_test = "#00ffff",
  solarized = solarized,
}

return colors
